"""V3 KPI score cards (dense theme):
  - build_scorecard_pdf : one-page card of KPI tiles (today or a completed day)
  - build_week_matrix   : color-coded matrix, KPIs (rows) x last 7 days (cols)
fpdf2 core fonts (Helvetica) are Latin-1 only, so every string routes through _s().
"""
from fpdf import FPDF
import datetime as dt
from config import ARO_TARGET, LHPC_TARGET, BIG4_GOAL, BIG4_AMBER

NAVY=(20,39,63);RED=(208,52,44);INK=(15,23,42);MUTE=(91,100,114);GREEN=(21,138,90)
AMBER=(181,118,17);LINE=(214,221,230);PURPLE=(108,79,182);SOFT=(245,247,250)
GBG=(233,245,239);ABG=(251,243,228);RBG=(251,236,234);WHITE=(255,255,255)

_SUBS={
    "−":"-", "–":"-", "—":"-", "•":"-",
    "‘":"'", "’":"'", "“":'"', "”":'"',
    "…":"...", "±":"+/-", "×":"x", "°":"deg",
    "→":"->", "←":"<-", "↑":"^", "↓":"v",
    "↗":"^", "↘":"v", "↖":"^", "↙":"v",
    " ":" ", " ":" ", " ":" ",
}
def _s(x):
    t=str(x)
    for k,v in _SUBS.items():
        t=t.replace(k,v)
    return t.encode("latin-1","ignore").decode("latin-1")

def _header(pdf,W,title,subtitle):
    pdf.set_fill_color(*NAVY);pdf.rect(10,10,W-20,20,"F")
    pdf.set_fill_color(*RED);pdf.rect(13,13,2,13,"F")
    pdf.set_xy(19,12);pdf.set_text_color(255,255,255);pdf.set_font("Helvetica","B",14)
    pdf.cell(0,7,_s(title),ln=1)
    pdf.set_xy(19,20);pdf.set_font("Helvetica","",9.5);pdf.set_text_color(210,222,235)
    pdf.cell(0,5,_s(subtitle),ln=1)

def build_scorecard_pdf(store_name,code,date_str,as_of,cards):
    """One-page card. `cards` = list of (label, value, sub, rgb). as_of may be '' for a
    completed-day card (shows 'Full day' instead of 'as of ...')."""
    pdf=FPDF("P","mm","Letter");pdf.set_auto_page_break(False);pdf.add_page();W=215.9
    tail=f"as of {as_of}" if as_of else "full day"
    _header(pdf,W,"VantEdge Auto  -  Store Scorecard",f"{store_name} (#{code})    {date_str}    {tail}")
    y,cols,gap,m=38,3,6,10;cw=(W-2*m-(cols-1)*gap)/cols;ch=28
    for i,(label,value,sub,rgb) in enumerate(cards):
        r,c=divmod(i,cols);x=m+c*(cw+gap);yy=y+r*(ch+gap)
        pdf.set_draw_color(*LINE);pdf.set_line_width(0.3);pdf.set_fill_color(255,255,255);pdf.rect(x,yy,cw,ch,"DF")
        pdf.set_fill_color(*rgb);pdf.rect(x,yy,cw,1.8,"F")
        pdf.set_xy(x+4,yy+4);pdf.set_text_color(*MUTE);pdf.set_font("Helvetica","",8);pdf.cell(cw-8,4,_s(label).upper())
        pdf.set_xy(x+4,yy+10);pdf.set_text_color(*INK);pdf.set_font("Helvetica","B",18);pdf.cell(cw-8,8,_s(value))
        pdf.set_xy(x+4,yy+20);pdf.set_text_color(*rgb);pdf.set_font("Helvetica","B",8);pdf.cell(cw-8,4,_s(sub or ""))
    ny=y+2*(ch+gap)+5
    pdf.set_xy(10,ny);pdf.set_text_color(*MUTE);pdf.set_font("Helvetica","I",7.5)
    pdf.multi_cell(W-20,4,_s("Big 4 is the overall attach % (Big 4 units / cars); the goal is 53% (the four item "
                             "targets summed). Comparison is vs a normal day for this weekday (simple 4-week "
                             "average). Generated by the Take 5 Scorecard."))
    return bytes(pdf.output())

# ---------- weekly matrix ----------
def _aro_rgb(v):   return (GREEN,GBG) if v>=ARO_TARGET else ((AMBER,ABG) if v>=ARO_TARGET*0.94 else (RED,RBG))
def _big4_rgb(v):  return (GREEN,GBG) if v>=BIG4_GOAL else ((AMBER,ABG) if v>=BIG4_AMBER else (RED,RBG))
def _lhpc_rgb(v):  return (GREEN,GBG) if v<=LHPC_TARGET else ((AMBER,ABG) if v<=1.25 else (RED,RBG))

def _day_label(iso):
    try:
        d=dt.date.fromisoformat(iso);return d.strftime("%a")+"\n"+f"{d.month}/{d.day}"
    except Exception:
        return _s(iso or "-")

def build_week_matrix(store_name,code,summaries):
    """Color-coded matrix PDF. `summaries` = list of calc.day_summary dicts (any order);
    displayed oldest -> newest across the columns. KPIs with a target are shaded
    green/amber/red; volume rows (Cars, Net, Diff %) are shown neutral as context."""
    days=[s for s in summaries if s]
    days.sort(key=lambda s:s.get("date") or "")
    pdf=FPDF("P","mm","Letter");pdf.set_auto_page_break(False);pdf.add_page();W=215.9
    span=f"{_day_label(days[0]['date']).replace(chr(10),' ')} - {_day_label(days[-1]['date']).replace(chr(10),' ')}" if days else "no data"
    _header(pdf,W,"VantEdge Auto  -  Weekly Scorecard",f"{store_name} (#{code})    last {len(days)} days    {span}")
    m=10;lw=34;n=len(days);cw=(W-2*m-lw)/max(n,1);y0=40;rh=13;hh=13
    # header row
    pdf.set_xy(m,y0);pdf.set_fill_color(*NAVY);pdf.rect(m,y0,lw,hh,"F")
    pdf.set_text_color(255,255,255);pdf.set_font("Helvetica","B",8);pdf.set_xy(m+2,y0+4);pdf.cell(lw-3,4,_s("METRIC"))
    for j,s in enumerate(days):
        x=m+lw+j*cw;pdf.set_fill_color(*NAVY);pdf.rect(x,y0,cw,hh,"F")
        lab=_day_label(s["date"]).split("\n");pdf.set_text_color(255,255,255);pdf.set_font("Helvetica","B",7.5)
        pdf.set_xy(x,y0+2);pdf.cell(cw,4,_s(lab[0]),align="C")
        if len(lab)>1:pdf.set_xy(x,y0+6.5);pdf.set_font("Helvetica","",7);pdf.cell(cw,4,_s(lab[1]),align="C")
    rows=[
        ("Cars",     lambda s:(f"{s['cars']:,}" if s['cars'] is not None else "-",(INK,WHITE))),
        ("ARO",      lambda s:(f"${s['aro']:,.0f}" if s['aro'] is not None else "-",_aro_rgb(s['aro']) if s['aro'] is not None else (MUTE,SOFT))),
        ("Net",      lambda s:(f"${s['net']:,.0f}" if s['net'] is not None else "-",(INK,WHITE))),
        ("Big 4 attach %",lambda s:(f"{s['big4']:.0f}%" if s['big4'] is not None else "-",_big4_rgb(s['big4']) if s['big4'] is not None else (MUTE,SOFT))),
        ("LHPC",     lambda s:(f"{s['lhpc']:.2f}" if s['lhpc'] is not None else "-",_lhpc_rgb(s['lhpc']) if s['lhpc'] is not None else (MUTE,SOFT))),
        ("Diff % cars",lambda s:(f"{s['diff_pct']:.0f}%" if s['diff_pct'] is not None else "-",(INK,WHITE))),
    ]
    for i,(name,fn) in enumerate(rows):
        yy=y0+hh+i*rh
        pdf.set_fill_color(*SOFT);pdf.set_draw_color(*LINE);pdf.set_line_width(0.2);pdf.rect(m,yy,lw,rh,"DF")
        pdf.set_text_color(*INK);pdf.set_font("Helvetica","B",8);pdf.set_xy(m+2,yy+rh/2-2);pdf.cell(lw-3,4,_s(name))
        for j,s in enumerate(days):
            x=m+lw+j*cw;val,(tc,bg)=fn(s)
            pdf.set_fill_color(*bg);pdf.rect(x,yy,cw,rh,"DF")
            pdf.set_text_color(*tc);pdf.set_font("Helvetica","B",8.5);pdf.set_xy(x,yy+rh/2-2);pdf.cell(cw,4,_s(val),align="C")
    ly=y0+hh+len(rows)*rh+6
    pdf.set_xy(10,ly);pdf.set_text_color(*MUTE);pdf.set_font("Helvetica","I",7.5)
    pdf.multi_cell(W-20,4,_s("Shaded cells are scored vs target: ARO vs $125, Big 4 attach vs the 53% goal (green >=53%, "
                             "amber >=32%), LHPC vs 1.10 (lower = leaner). Cars, Net and Diff % are shown as volume context "
                             "(no target). Each day is its end-of-day total. Generated by the Take 5 Scorecard."))
    return bytes(pdf.output())
