"""V3 KPI score cards (dense theme):
  - build_scorecard_pdf : one-page card of KPI tiles (today or a completed day)
  - build_week_matrix   : color-coded matrix, KPIs (rows) x last 7 days (cols)
fpdf2 core fonts (Helvetica) are Latin-1 only, so every string routes through _s().
"""
from fpdf import FPDF
import datetime as dt
from config import ARO_TARGET, LHPC_TARGET, BIG4_GOAL, BIG4_AMBER

NAVY=(20,39,63);RED=(208,52,44);INK=(15,23,42);MUTE=(91,100,114);GREEN=(21,138,90)
AMBER=(181,118,17);LINE=(214,221,230);PURPLE=(108,79,182);SOFT=(245,247,250)
GBG=(233,245,239);ABG=(251,243,228);RBG=(251,236,234);WHITE=(255,255,255)

_SUBS={
    "−":"-", "–":"-", "—":"-", "•":"-",
    "‘":"'", "’":"'", "“":'"', "”":'"',
    "…":"...", "±":"+/-", "×":"x", "°":"deg",
    "→":"->", "←":"<-", "↑":"^", "↓":"v",
    "↗":"^", "↘":"v", "↖":"^", "↙":"v",
    " ":" ", " ":" ", " ":" ",
}
def _s(x):
    t=str(x)
    for k,v in _SUBS.items():
        t=t.replace(k,v)
    return t.encode("latin-1","ignore").decode("latin-1")

def _grade_rgb(letter):
    if not letter or letter=="-": return (MUTE,SOFT)
    if letter in ("A","B"): return (GREEN,GBG)
    if letter in ("C","D"): return (AMBER,ABG)
    return (RED,RBG)

def _header(pdf,W,title,subtitle):
    pdf.set_fill_color(*NAVY);pdf.rect(10,10,W-20,20,"F")
    pdf.set_fill_color(*RED);pdf.rect(13,13,2,13,"F")
    pdf.set_xy(19,12);pdf.set_text_color(255,255,255);pdf.set_font("Helvetica","B",14)
    pdf.cell(0,7,_s(title),ln=1)
    pdf.set_xy(19,20);pdf.set_font("Helvetica","",9.5);pdf.set_text_color(210,222,235)
    pdf.cell(0,5,_s(subtitle),ln=1)

def build_scorecard_pdf(store_name,code,date_str,as_of,cards,grade=None):
    """One-page card. `cards` = list of (label, value, sub, rgb). as_of may be '' for a
    completed-day card (shows 'Full day' instead of 'as of ...'). `grade` is accepted for
    call-site compatibility but intentionally NOT drawn — downloadable reports omit the
    letter grade (it lives only on the on-screen dashboard)."""
    pdf=FPDF("P","mm","Letter");pdf.set_auto_page_break(False);pdf.add_page();W=215.9
    tail=f"as of {as_of}" if as_of else "full day"
    _header(pdf,W,"VantEdge Auto  -  Store Scorecard",f"{store_name} (#{code})    {date_str}    {tail}")
    y,cols,gap,m=38,3,6,10;cw=(W-2*m-(cols-1)*gap)/cols;ch=28
    for i,(label,value,sub,rgb) in enumerate(cards):
        r,c=divmod(i,cols);x=m+c*(cw+gap);yy=y+r*(ch+gap)
        pdf.set_draw_color(*LINE);pdf.set_line_width(0.3);pdf.set_fill_color(255,255,255);pdf.rect(x,yy,cw,ch,"DF")
        pdf.set_fill_color(*rgb);pdf.rect(x,yy,cw,1.8,"F")
        pdf.set_xy(x+4,yy+4);pdf.set_text_color(*MUTE);pdf.set_font("Helvetica","",8);pdf.cell(cw-8,4,_s(label).upper())
        pdf.set_xy(x+4,yy+10);pdf.set_text_color(*INK);pdf.set_font("Helvetica","B",18);pdf.cell(cw-8,8,_s(value))
        pdf.set_xy(x+4,yy+20);pdf.set_text_color(*rgb);pdf.set_font("Helvetica","B",8);pdf.cell(cw-8,4,_s(sub or ""))
    ny=y+2*(ch+gap)+5
    pdf.set_xy(10,ny);pdf.set_text_color(*MUTE);pdf.set_font("Helvetica","I",7.5)
    pdf.multi_cell(W-20,4,_s("Big 4 is the average of the four items' attach rates (each = its units / cars); the goal "
                             "is 13% (the average of the four item targets). Comparison is vs a normal day for this "
                             "weekday (simple 4-week average). Generated by the Take 5 Scorecard."))
    return bytes(pdf.output())

# ---------- weekly matrix ----------
def _aro_rgb(v):   return (GREEN,GBG) if v>=ARO_TARGET else ((AMBER,ABG) if v>=ARO_TARGET*0.94 else (RED,RBG))
def _big4_rgb(v):  return (GREEN,GBG) if v>=BIG4_GOAL else ((AMBER,ABG) if v>=BIG4_AMBER else (RED,RBG))
def _lhpc_rgb(v):  return (GREEN,GBG) if v<=LHPC_TARGET else ((AMBER,ABG) if v<=1.25 else (RED,RBG))

def _day_label(iso):
    try:
        d=dt.date.fromisoformat(iso);return d.strftime("%a")+"\n"+f"{d.month}/{d.day}"
    except Exception:
        return _s(iso or "-")

def build_week_matrix(store_name,code,summaries):
    """Weekly matrix PDF: rows = KPIs, a fixed TARGET column, one column per day showing
    the actual (with its diff vs target on graded rows), and a bottom GRADE row (one
    letter per day). ARO/Big 4/LHPC are shaded green/amber/red vs target; Cars/Net/Diff
    are context (no target, not graded). `summaries` = calc.day_summary dicts."""
    days=[s for s in summaries if s]
    days.sort(key=lambda s:s.get("date") or "")
    pdf=FPDF("P","mm","Letter");pdf.set_auto_page_break(False);pdf.add_page();W=215.9
    span=f"{_day_label(days[0]['date']).replace(chr(10),' ')} - {_day_label(days[-1]['date']).replace(chr(10),' ')}" if days else "no data"
    _header(pdf,W,"VantEdge Auto  -  Weekly Scorecard",f"{store_name} (#{code})    last {len(days)} days    {span}")
    m=10; lw=30; tw=16; n=len(days); cw=(W-2*m-lw-tw)/max(n,1); y0=40; hh=12; rh=15
    # header row: METRIC | TARGET | day labels
    pdf.set_fill_color(*NAVY);pdf.rect(m,y0,lw,hh,"F");pdf.set_text_color(255,255,255)
    pdf.set_font("Helvetica","B",8);pdf.set_xy(m+2,y0+4);pdf.cell(lw-3,4,_s("METRIC"))
    pdf.set_fill_color(*NAVY);pdf.rect(m+lw,y0,tw,hh,"F");pdf.set_xy(m+lw,y0+4);pdf.cell(tw,4,_s("TARGET"),align="C")
    for j,s in enumerate(days):
        x=m+lw+tw+j*cw;pdf.set_fill_color(*NAVY);pdf.rect(x,y0,cw,hh,"F")
        lab=_day_label(s["date"]).split("\n");pdf.set_text_color(255,255,255);pdf.set_font("Helvetica","B",7.5)
        pdf.set_xy(x,y0+1.5);pdf.cell(cw,4,_s(lab[0]),align="C")
        if len(lab)>1:pdf.set_xy(x,y0+6);pdf.set_font("Helvetica","",7);pdf.cell(cw,4,_s(lab[1]),align="C")
    ROWS=[
        dict(name="Cars",tgt="-",val=lambda s:(f"{s['cars']:,}" if s['cars'] is not None else "-"),diff=None,shade=None),
        dict(name="ARO",tgt="$125",val=lambda s:(f"${s['aro']:,.0f}" if s['aro'] is not None else "-"),
             diff=lambda s:(("%+d"%round(s['aro']-ARO_TARGET)) if s['aro'] is not None else ""),
             shade=lambda s:(_aro_rgb(s['aro']) if s['aro'] is not None else (MUTE,SOFT))),
        dict(name="Net",tgt="-",val=lambda s:(f"${s['net']:,.0f}" if s['net'] is not None else "-"),diff=None,shade=None),
        dict(name="Big 4 avg %",tgt="13%",val=lambda s:(f"{s['big4']:.0f}%" if s['big4'] is not None else "-"),
             diff=lambda s:(("%+d pt"%round(s['big4']-BIG4_GOAL)) if s['big4'] is not None else ""),
             shade=lambda s:(_big4_rgb(s['big4']) if s['big4'] is not None else (MUTE,SOFT))),
        dict(name="LHPC",tgt="1.10",val=lambda s:(f"{s['lhpc']:.2f}" if s['lhpc'] is not None else "-"),
             diff=lambda s:(("%+.2f"%(s['lhpc']-LHPC_TARGET)) if s['lhpc'] is not None else ""),
             shade=lambda s:(_lhpc_rgb(s['lhpc']) if s['lhpc'] is not None else (MUTE,SOFT))),
        dict(name="Diff % cars",tgt="-",val=lambda s:(f"{s['diff_pct']:.0f}%" if s['diff_pct'] is not None else "-"),diff=None,shade=None),
    ]
    y=y0+hh
    for R in ROWS:
        pdf.set_fill_color(*SOFT);pdf.set_draw_color(*LINE);pdf.set_line_width(0.2);pdf.rect(m,y,lw,rh,"DF")
        pdf.set_text_color(*INK);pdf.set_font("Helvetica","B",8);pdf.set_xy(m+2,y+rh/2-2);pdf.cell(lw-3,4,_s(R["name"]))
        pdf.set_fill_color(255,255,255);pdf.rect(m+lw,y,tw,rh,"DF")
        pdf.set_text_color(*MUTE);pdf.set_font("Helvetica","",8);pdf.set_xy(m+lw,y+rh/2-2);pdf.cell(tw,4,_s(R["tgt"]),align="C")
        for j,s in enumerate(days):
            x=m+lw+tw+j*cw; tc,bg=(R["shade"](s) if R["shade"] else (INK,WHITE))
            pdf.set_fill_color(*bg);pdf.rect(x,y,cw,rh,"DF")
            pdf.set_text_color(*tc);pdf.set_font("Helvetica","B",8.5)
            if R["diff"]:
                pdf.set_xy(x,y+2.6);pdf.cell(cw,4,_s(R["val"](s)),align="C")
                pdf.set_text_color(*MUTE);pdf.set_font("Helvetica","",6.5);pdf.set_xy(x,y+7.8);pdf.cell(cw,3,_s(R["diff"](s)),align="C")
            else:
                pdf.set_xy(x,y+rh/2-2);pdf.cell(cw,4,_s(R["val"](s)),align="C")
        y+=rh
    pdf.set_xy(10,y+6);pdf.set_text_color(*MUTE);pdf.set_font("Helvetica","I",7.2)
    pdf.multi_cell(W-20,4,_s("Cells: actual, with the diff vs target beneath on graded rows; shaded green/amber/red vs target "
                             "(ARO $125, Big 4 13%, LHPC 1.10 - lower is leaner). Cars, Net and Diff % are context (no target). "
                             "Each day is its end-of-day total. Generated by the Take 5 Scorecard."))
    return bytes(pdf.output())
