"""Server-side one-page KPI score card as a real PDF (fpdf2). Returned as bytes for
st.download_button. KPI cards only - no graphs - matching the on-screen strip."""
from fpdf import FPDF

NAVY = (20, 39, 63); RED = (228, 0, 43); INK = (31, 42, 55)
MUTE = (91, 107, 127); GREEN = (30, 142, 78); LINE = (210, 217, 227); PURPLE = (108, 79, 182)


def build_scorecard_pdf(store_name, code, date_str, as_of, cards):
    """One-page KPI score card (no projections/bottom-line). cards: 6 tuples of
    (label, value_str, sub_str, rgb) rendered symmetric 3x2. Timestamped."""
    pdf = FPDF(orientation="P", unit="mm", format="Letter")
    pdf.set_auto_page_break(False)
    pdf.add_page()
    W = 215.9
    pdf.set_fill_color(*NAVY); pdf.rect(10, 10, W - 20, 22, "F")
    pdf.set_fill_color(*RED); pdf.rect(14, 14, 2.2, 14, "F")
    pdf.set_xy(20, 13); pdf.set_text_color(255, 255, 255); pdf.set_font("Helvetica", "B", 15)
    pdf.cell(0, 7, "VantEdge Auto  -  Store Scorecard", ln=1)
    pdf.set_xy(20, 21); pdf.set_font("Helvetica", "", 10); pdf.set_text_color(220, 229, 240)
    pdf.cell(0, 6, f"{store_name} ({code})    {date_str}    as of {as_of}", ln=1)

    y, cols, gap, m = 42, 3, 6, 10
    cw = (W - 2 * m - (cols - 1) * gap) / cols
    ch = 30
    for i, (label, value, sub, rgb) in enumerate(cards):
        r, c = divmod(i, cols)
        x = m + c * (cw + gap); yy = y + r * (ch + gap)
        pdf.set_draw_color(*LINE); pdf.set_line_width(0.3); pdf.set_fill_color(255, 255, 255)
        pdf.rect(x, yy, cw, ch, "DF")
        pdf.set_fill_color(*rgb); pdf.rect(x, yy, cw, 2, "F")
        pdf.set_xy(x + 5, yy + 5); pdf.set_text_color(*MUTE); pdf.set_font("Helvetica", "", 8.5)
        pdf.cell(cw - 10, 4, label.upper())
        pdf.set_xy(x + 5, yy + 11); pdf.set_text_color(*INK); pdf.set_font("Helvetica", "B", 20)
        pdf.cell(cw - 10, 9, str(value))
        pdf.set_xy(x + 5, yy + 22); pdf.set_text_color(*rgb); pdf.set_font("Helvetica", "B", 8.5)
        pdf.cell(cw - 10, 4, sub or "")
    ny = y + 2 * (ch + gap) + 6
    pdf.set_xy(10, ny); pdf.set_text_color(*MUTE); pdf.set_font("Helvetica", "I", 8)
    pdf.multi_cell(W - 20, 4, "Pace is measured against a normal day for this weekday. "
                              "Generated by the Take 5 Scorecard.")
    return bytes(pdf.output())
